/**
 * ESM bridge to the CJS pricing tools library.
 *
 * The pricing engine (tools/pricing/lib/) uses CommonJS + better-sqlite3
 * native addon. We use createRequire to load it from Next.js API routes.
 *
 * On Vercel, /var/task is read-only — SQLite's WAL journaling can't write
 * its sidecar files there. This module downloads pricing.db from S3 to
 * /tmp on cold start (the only writable location on Vercel functions),
 * then opens it read-only without WAL. Local dev + EC2 use the on-disk
 * path with WAL as before.
 *
 * Usage:
 *   import { getPricingLib, getDb } from '@/lib/pricing-db';
 *   const { db, stats, multiStay, dates, normalize } = getPricingLib();
 */

import { createRequire } from 'module';
import { existsSync, statSync, writeFileSync } from 'fs';

const _require = createRequire(import.meta.url);

let _cached = null;
let _initialized = false;

const TMP_DB_PATH = '/tmp/pricing.db';
const TTL_MS = 24 * 60 * 60 * 1000; // re-download from S3 if file > 24h old
const S3_BUCKET = 'casa-coqui-pricing-data';
const S3_KEY = 'pricing.db';

async function fetchPricingDbFromS3() {
  // Lazy-import the SDK so non-Vercel environments don't pay for it on
  // module load. AWS SDK v3 is tree-shakable; the resolved bundle is small.
  const { S3Client, GetObjectCommand } = await import('@aws-sdk/client-s3');
  const s3 = new S3Client({
    region: process.env.AWS_DEFAULT_REGION || 'us-east-1',
  });
  const response = await s3.send(
    new GetObjectCommand({ Bucket: S3_BUCKET, Key: S3_KEY })
  );
  const buffer = await response.Body.transformToByteArray();
  writeFileSync(TMP_DB_PATH, Buffer.from(buffer));
}

async function ensureRuntimeDb() {
  if (process.env.PRICING_DB_PATH) return;
  if (!process.env.VERCEL) return; // local + EC2 use the cwd path directly

  if (existsSync(TMP_DB_PATH)) {
    const age = Date.now() - statSync(TMP_DB_PATH).mtimeMs;
    if (age < TTL_MS) {
      process.env.PRICING_DB_PATH = TMP_DB_PATH;
      return;
    }
  }

  await fetchPricingDbFromS3();
  process.env.PRICING_DB_PATH = TMP_DB_PATH;
}

// Top-level await: block module load until /tmp/pricing.db is in place.
// Cold start cost is ~200ms on Vercel for the 8MB download (plus an extra
// hop on AWS SDK init). Subsequent invocations on the same warm instance
// reuse the cached file. Failures here surface immediately as module
// load errors with a clear S3 stack trace, instead of an opaque
// SQLITE_CANTOPEN inside an API route handler.
if (process.env.VERCEL) {
  await ensureRuntimeDb();
}

/**
 * Lazy-load all CJS pricing modules. Cached after first call.
 * Returns { db, stats, multiStay, dates, normalize }
 */
export function getPricingLib() {
  if (_cached) return _cached;

  /* eslint-disable no-undef -- createRequire paths resolved at runtime */
  const db = _require('../tools/pricing/lib/db.js');
  const stats = _require('../tools/pricing/lib/stats.js');
  const multiStay = _require('../tools/pricing/lib/multi-stay.js');
  const dates = _require('../tools/pricing/lib/dates.js');
  const normalize = _require('../tools/pricing/lib/normalize.js');
  const decisionEngine = _require('../tools/pricing/lib/decision-engine.js');
  const availability = _require('../tools/pricing/lib/availability.js');
  const seasons = _require('../tools/pricing/lib/seasons.js');
  const compTimeline = _require('../tools/pricing/lib/comp-timeline.js');
  /* eslint-enable no-undef */

  _cached = { db, stats, multiStay, dates, normalize, decisionEngine, availability, seasons, compTimeline };
  return _cached;
}

/**
 * Shorthand: get the better-sqlite3 Database instance.
 *
 * On Vercel: PRICING_DB_PATH points at /tmp/pricing.db (downloaded from
 * S3 in top-level await above) and tools/pricing/lib/db.js opens it
 * read-only (no WAL). Schema/migration init is skipped — the DB
 * downloaded from S3 was generated by autopilot with the latest schema.
 *
 * On local/EC2: opens the on-disk path with WAL enabled and runs schema
 * + migrations in case the DB is fresh.
 */
export function getDb() {
  const dbLib = getPricingLib().db;
  const db = dbLib.getDb();

  if (_initialized || process.env.VERCEL) return db;

  // Init only on writable filesystems where the autopilot might be
  // bootstrapping a fresh DB on this same disk.
  /* eslint-disable no-undef */
  const { readFileSync } = _require('fs');
  const { join } = _require('path');
  /* eslint-enable no-undef */

  const schemaPath = join(process.cwd(), 'tools', 'pricing', 'schema.sql');
  const schema = readFileSync(schemaPath, 'utf8');
  db.exec(schema);

  for (const mig of ['migrate-v3.sql', 'migrate-v4.sql', 'migrate-v5.sql', 'migrate-v6.sql', 'migrate-v7.sql', 'migrate-v8.sql', 'migrate-v9.sql', 'migrate-v10.sql', 'migrate-v11.sql', 'migrate-v12.sql', 'migrate-v13.sql', 'migrate-v14.sql', 'migrate-v15.sql']) {
    const migratePath = join(process.cwd(), 'tools', 'pricing', mig);
    try {
      const migration = readFileSync(migratePath, 'utf8');
      const stripped = migration.split('\n').filter(l => !l.trimStart().startsWith('--')).join('\n');
      const stmts = stripped.split(';').map(s => s.trim()).filter(Boolean);
      for (const stmt of stmts) {
        try { db.exec(stmt); } catch { /* already exists */ }
      }
    } catch { /* file not found — skip */ }
  }

  _initialized = true;
  return db;
}
